#!/bin/python

# execute
#
# Copyright (C) 2017 naheel_azawy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import os.path
import sys
import shlex
import platform
import re

TEST = False
SHOW_COMMANDS = False

COMPARGS = "--compargs"
MOREFILES = "--morefiles"
LINES_FROM = "--from"
LINES_TO = "--to"

COMPARGS_S = "-c"
MOREFILES_S = "-m"
LINES_FROM_S = "-f"
LINES_TO_S = "-t"


def replace_last(src, rep, rwith):
    """
    Replace last occurrence
    """
    index = src.rfind(rep)
    return src[:index] + src[index:].replace(rep, rwith)


def main():
    fr = 0
    to = 0
    frb = False
    tob = False
    cmArgs = ""
    cmFiles = ""
    rnArgs = ""
    s = ""

    argstr = ""
    argc = len(sys.argv)
    for a in range(0, argc - 1):
        argstr += sys.argv[a] + " "
    argstr += "\'" + sys.argv[argc - 1] + "\'"
    args = shlex.split(argstr)

    if TEST:
        print argstr
        i = 0
        for a in args:
            print str(i) + "- " + a
            i += 1
        print "--------------"

    i = 1
    while i < len(args):
        if args[i] == COMPARGS or args[i] == COMPARGS_S:
            cmArgs += " " + args[i + 1]
            i += 1
        elif args[i] == MOREFILES or args[i] == MOREFILES_S:
            cmFiles += " " + args[i + 1]
            i += 1
        elif args[i] == LINES_FROM or args[i] == LINES_FROM_S:
            fr = int(args[i + 1]) - 1
            frb = True
            i += 1
        elif args[i] == LINES_TO or args[i] == LINES_TO_S:
            to = int(args[i + 1])
            tob = True
            i += 1
        elif s == "" and os.path.exists(args[i]):
            s = os.path.abspath(args[i])
        else:
            rnArgs += " " + args[i]
        i += 1

    sh = False

    with open(s, 'r') as fin:
        data = fin.read().splitlines(True)

    argsSearch = re.search("#!.*/execute(.*)", data[0])
    if argsSearch:
        argstr = argsSearch.group(1)
        data[0] = "\n"
        sh = True
        args2 = shlex.split(argstr)
        if args[1:len(args) - 1] != args2:
            args = args2
            i = 0
            while i < len(args):
                if args[i] == COMPARGS or args[i] == COMPARGS_S:
                    cmArgs += " " + args[i + 1]
                    i += 1
                elif args[i] == MOREFILES or args[i] == MOREFILES_S:
                    cmFiles += " " + args[i + 1]
                    i += 1
                elif args[i] == LINES_FROM or args[i] == LINES_FROM_S:
                    fr = int(args[i + 1]) - 1
                    frb = True
                    i += 1
                elif args[i] == LINES_TO or args[i] == LINES_TO_S:
                    to = int(args[i + 1])
                    tob = True
                    i += 1
                else:
                    rnArgs += " " + args[i]
                i += 1

            if TEST:
                print "argstr: " + argstr
                i = 0
                for a in args:
                    print "bang " + str(i) + "- " + a
                    i += 1
                print "--------------"

    n = s[s.rfind('/') + 1:]
    p = s[:s.rfind('/') + 1]
    e = s[s.rfind('.'):]
    bp = os.path.expanduser('~') + "/.execs/" + p + "/"
    t = bp + "." + n + ".tmp"
    inputFiles = "\'" + s + "\'" + cmFiles.replace("$p", p)
    b = ""
    cm = ""
    rn = ""

    if e == ".java":
        c = replace_last(n, e, "")
        b = "\'" + bp + c + ".class" + "\'"
        cm = "javac " + inputFiles + " && " + "mv " + \
            (p + c + "*.class").replace(" ", "\\ ") + " '" + bp + "'"
        rn = "cd \"" + bp + "\" && java " + c
    elif e == ".kt":
        b = "\'" + bp + replace_last(n, e, ".jar") + "\'"
        cm = "kotlinc " + inputFiles + " -include-runtime -d " + b
        rn = "cd \"" + bp + "\" && java -jar " + b
    elif e in (".vala", ".gs"):
        b = "\'" + bp + n + ".bin" + "\'"
        cm = "valac " + inputFiles + " -o " + b
        rn = b
    elif e == ".c":
        b = "\'" + bp + n + ".bin" + "\'"
        cm = "gcc " + inputFiles + " -o " + b
        rn = b
    elif e in (".cpp", ".C", ".cc", ".CPP", ".c++", ".cp", ".cxx"):
        b = "\'" + bp + n + ".bin" + "\'"
        cm = "g++ " + inputFiles + " -o " + b
        rn = b
    elif e == ".cs":
        b = "\'" + bp + replace_last(n, e, ".exe") + "\'"
        cm = "mcs " + inputFiles + " -out:" + b
        rn = "mono " + b
    elif e == ".vb":
        b = "\'" + bp + replace_last(n, e, ".exe") + "\'"
        cm = "vbnc " + inputFiles + " 1>/dev/null /out:" + b
        rn = "mono " + b
    elif e == ".rs":
        b = "\'" + bp + n + ".bin" + "\'"
        cm = "rustc " + inputFiles + " -o " + b
        rn = b
    elif e == ".go":
        b = "\'" + bp + n + ".bin" + "\'"
        cm = "gccgo " + inputFiles + " -o " + b
        rn = b
    elif e == ".ts":
        b = "\'" + bp + replace_last(n, e, ".js") + "\'"
        cm = "tsc " + inputFiles + " && mv " + \
            replace_last(s, e, ".js") + " " + bp
        rn = "node " + b
    elif e == ".asm":
        b = "\'" + bp + n + ".bin" + "\'"
        o = "\'" + bp + n + ".o" + "\'"
        cm = "nasm " + inputFiles + " -o " + o + " -f elf"
        if platform.architecture()[0] == "64bit":
            cm += "64"
        cm += " && ld -s -o " + b + " " + o
        cm += " && rm " + o
        rn = b
    elif e == ".py":
        b = "\'" + s + "\'"
        cm = ""
        rn = "python " + b
    elif e == ".js":
        b = "\'" + s + "\'"
        cm = ""
        rn = "node " + b
    elif e == ".m":
        b = "\'" + s + "\'"
        cm = ""
        rn = "octave --persist --no-gui --quiet " + b
    elif e == ".kts":
        b = "\'" + s + "\'"
        cm = ""
        rn = "kotlinc -script " + b
    else:
        print "Invalid input file: '" + s + "'"
        if not TEST:
            quit()

    if cm != "":
        cm += cmArgs
    rn += rnArgs

    if TEST:
        print(
            "fr = " + str(fr) + "\n"
            "to = " + str(to) + "\n"
            "s  = " + s + "\n"
            "n  = " + n + "\n"
            "p  = " + p + "\n"
            "e  = " + e + "\n"
            "bp = " + bp + "\n"
            "t  = " + t + "\n"
            "b  = " + b + "\n"
            "cm = " + cm + "\n"
            "rn = " + rn + "\n"
            "cmArgs = " + cmArgs + "\n"
            "rnArgs = " + rnArgs + "\n"
            "cmFiles = " + cmFiles + "\n"
            "--------------\n"
        )
        # quit()

    def run():
        """
        Run the bin if it exists and its has a last modified date that is newer than the source
        """
        b2 = b[1:len(b) - 1]
        if os.path.exists(b2) and os.path.getmtime(b2) >= os.path.getmtime(s):
            if SHOW_COMMANDS:
                print("> " + rn)
            os.system(rn)
            return True
        return False

    if frb or tob:
        os.system("rm -f " + b)

    if not run():
        """
        Compile the source. If it starts with '#!', remove it and generate a temp file
        """
        os.system("mkdir -p \'" + bp + "\'")
        genTemp = sh or frb or tob
        if genTemp:
            os.rename(s, t)
            if not tob:
                to = len(data)
            with open(s, 'w') as fout:
                fout.writelines(data[fr:to])
        if SHOW_COMMANDS:
            print("> " + cm)
        os.system(cm)
        if genTemp:
            os.rename(t, s)
        run()

    if frb or tob:
        os.system("rm -f " + b)


if __name__ == "__main__":
    main()
