#!/bin/bash
cd test
chmod +x HelloIntelAsm.asm
chmod +x HelloC.c
chmod +x HelloCpp.cpp
chmod +x HelloCS.cs
chmod +x HelloVBNet.vb
chmod +x HelloGo.go
chmod +x HelloRust.rs
chmod +x HelloJava.java
chmod +x HelloTS.ts
chmod +x HelloGenie.gs
chmod +x HelloVala.vala
chmod +x HelloValaGtk.vala

./HelloIntelAsm.asm
./HelloC.c
./HelloCpp.cpp
./HelloCS.cs
./HelloVBNet.vb
./HelloGo.go
./HelloRust.rs
./HelloJava.java
./HelloTS.ts
./HelloGenie.gs
./HelloVala.vala
./HelloValaGtk.vala
